// <auto-generated />
using System;
using CinemasRafa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemasRafa.Migrations
{
    [DbContext(typeof(ControlContext))]
    [Migration("20220610150147_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CinemasRafa.DTOs.AdminDto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("AdminDto");
                });

            modelBuilder.Entity("CinemasRafa.DTOs.CustomerDto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("CustomerDto");
                });

            modelBuilder.Entity("CinemasRafa.DTOs.WorkerDto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("WorkerDto");
                });

            modelBuilder.Entity("CinemasRafa.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CuentaUsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ID");

                    b.HasIndex("CuentaUsuarioID");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CuentaUsuarioID = 1,
                            Name = "admin",
                            Phone = "642443212",
                            Surname = "min"
                        },
                        new
                        {
                            ID = 2,
                            CuentaUsuarioID = 2,
                            Name = "administrador",
                            Phone = "642443213",
                            Surname = "pp"
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ficcion"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Accion"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Terror"
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.CuentaUsuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("CuentaUsuario");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            Email = "admin1@hotmail.com",
                            Password = "QQBsAHQAYQBpAHIAMQAyADMAJAAlAA==",
                            RoleID = 1,
                            Username = "admin1"
                        },
                        new
                        {
                            ID = 2,
                            Active = false,
                            Email = "admin2@hotmail.com",
                            Password = "QQBsAHQAYQBpAHIAMQAyADMAJAAlAA==",
                            RoleID = 1,
                            Username = "admin2"
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            Email = "customer1@hotmail.com",
                            Password = "QQBsAHQAYQBpAHIAMQAyADMAJAAlAA==",
                            RoleID = 3,
                            Username = "customer1"
                        },
                        new
                        {
                            ID = 4,
                            Active = false,
                            Email = "customer2@hotmail.com",
                            Password = "QQBsAHQAYQBpAHIAMQAyADMAJAAlAA==",
                            RoleID = 3,
                            Username = "customert2"
                        },
                        new
                        {
                            ID = 5,
                            Active = true,
                            Email = "worker1@hotmail.com",
                            Password = "QQBsAHQAYQBpAHIAMQAyADMAJAAlAA==",
                            RoleID = 2,
                            Username = "worker1"
                        },
                        new
                        {
                            ID = 6,
                            Active = false,
                            Email = "worker2@hotmail.com",
                            Password = "QQBsAHQAYQBpAHIAMQAyADMAJAAlAA==",
                            RoleID = 2,
                            Username = "worker2"
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("CuentaUsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ID");

                    b.HasIndex("CuentaUsuarioID");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Avenida M",
                            CuentaUsuarioID = 3,
                            Name = "customer",
                            Phone = "642443234",
                            Surname = "custo"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Avenida M",
                            CuentaUsuarioID = 4,
                            Name = "customer",
                            Phone = "642443265",
                            Surname = "custo"
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("longtext");

                    b.Property<string>("Controller")
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Action = "Index",
                            Controller = "CuentaUsuarios",
                            Label = "Cuentas"
                        },
                        new
                        {
                            ID = 2,
                            Action = "Index",
                            Controller = "Admins",
                            Label = "Administradores"
                        },
                        new
                        {
                            ID = 3,
                            Action = "Index",
                            Controller = "Worker",
                            Label = "Workers"
                        },
                        new
                        {
                            ID = 4,
                            Action = "Index",
                            Controller = "Customer",
                            Label = "Customer"
                        },
                        new
                        {
                            ID = 5,
                            Action = "Index",
                            Controller = "Menus",
                            Label = "Menus"
                        },
                        new
                        {
                            ID = 6,
                            Action = "Index",
                            Controller = "RoleHasMenus",
                            Label = "RoleMenus"
                        },
                        new
                        {
                            ID = 7,
                            Action = "Index",
                            Controller = "Roles",
                            Label = "Roles"
                        },
                        new
                        {
                            ID = 8,
                            Action = "Index",
                            Controller = "Pegis",
                            Label = "Pegis"
                        },
                        new
                        {
                            ID = 9,
                            Action = "Index",
                            Controller = "Peliculas",
                            Label = "Peliculas"
                        },
                        new
                        {
                            ID = 10,
                            Action = "Index",
                            Controller = "Series",
                            Label = "Series"
                        },
                        new
                        {
                            ID = 11,
                            Action = "Index",
                            Controller = "Categorias",
                            Label = "Categorias"
                        },
                        new
                        {
                            ID = 12,
                            Action = "Index",
                            Controller = "AdminControlPeliculas",
                            Label = "Control Peliculas"
                        },
                        new
                        {
                            ID = 13,
                            Action = "Index",
                            Controller = "AdminControlSeries",
                            Label = "Control Series"
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Pegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EdadMin")
                        .HasColumnType("longtext");

                    b.Property<int>("PegiEdad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pegi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EdadMin = "Pegi 3",
                            PegiEdad = 3
                        },
                        new
                        {
                            Id = 5,
                            EdadMin = "Pegi 7",
                            PegiEdad = 7
                        },
                        new
                        {
                            Id = 2,
                            EdadMin = "Pegi 12",
                            PegiEdad = 12
                        },
                        new
                        {
                            Id = 3,
                            EdadMin = "Pegi 16",
                            PegiEdad = 16
                        },
                        new
                        {
                            Id = 4,
                            EdadMin = "Pegi 18",
                            PegiEdad = 18
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Director")
                        .HasColumnType("longtext");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<int>("PegiId")
                        .HasColumnType("int");

                    b.Property<string>("UrlDescarga")
                        .HasColumnType("longtext");

                    b.Property<double>("Valoracion")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PegiId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Por primera vez en la historia cinematográfica de Spider-Man, nuestro héroe, vecino y amigo es desenmascarado, y por tanto, ya no es capaz de separar su vida normal de los enormes riesgos que conlleva ser un superhéroe. Cuando pide ayuda al Doctor Strange, los riesgos pasan a ser aún más peligrosos, obligándole a descubrir lo que realmente significa ser él. Secuela de 'Spider-Man: Far From Home'. ",
                            Director = "Jon Watts",
                            Duracion = 148,
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageUrl = "https://es.web.img2.acsta.net/r_1920_1080/pictures/21/12/01/12/07/0243323.jpg",
                            Nombre = "Spider-Man: No Way Home",
                            PegiId = 2,
                            UrlDescarga = "https://es.web.img3.acsta.net/c_200_200/pictures/15/11/24/16/53/595385.jpg",
                            Valoracion = 5.0
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Tras la muerte de sus padres, Peter Parker, un tímido estudiante, vive con su tía May y su tío Ben. Precisamente debido a su retraimiento no es un chico muy popular en el instituto. Un día le muerde una araña que ha sido modificada genéticamente; a la mañana siguiente, descubre estupefacto que posee la fuerza y la agilidad de ese insecto. Las aventuras del hombre araña se basan en el famoso cómic de Stan Lee y Steve Ditko.",
                            Director = "Sam Raimi",
                            Duracion = 121,
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageUrl = "https://es.web.img2.acsta.net/r_1920_1080/medias/nmedia/00/00/00/33/spiderman.jpg",
                            Nombre = "Spider-Man",
                            PegiId = 3,
                            UrlDescarga = "https://es.web.img2.acsta.net/r_1920_1080/medias/nmedia/00/00/00/33/spiderman.jpg",
                            Valoracion = 5.0
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descripcion = "Un joven hastiado de su gris y monótona vida lucha contra el insomnio. En un viaje en avión conoce a un carismático vendedor de jabón que sostiene una teoría muy particular: el perfeccionismo es cosa de gentes débiles; sólo la autodestrucción hace que la vida merezca la pena. Ambos deciden entonces fundar un club secreto de lucha, donde poder descargar sus frustaciones y su ira, que tendrá un éxito arrollador.",
                            Director = "David Fincher",
                            Duracion = 139,
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageUrl = "https://es.web.img3.acsta.net/r_1920_1080/img/23/b7/23b757ce995171ae05ba7449c67a47dc.jpg",
                            Nombre = "Club de la lucha",
                            PegiId = 5,
                            UrlDescarga = "https://es.web.img3.acsta.net/c_200_200/pictures/15/11/24/16/53/595385.jpg",
                            Valoracion = 5.0
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Han pasado dos años desde que el tranquilo Peter Parker dejó a Mary Jane Watson, su gran amor, y decidió seguir asumiendo sus responsabilidades como Spider-Man. Peter debe afrontar nuevos desafíos mientras lucha contra el don y la maldición de sus poderes equilibrando sus dos identidades: el escurridizo superhéroe Spider-Man y el estudiante universitario. Las relaciones con las personas que más aprecia están ahora en peligro de ser descubiertas con la aparición del poderoso villano de múltiples tentáculos Doctor Octopus, Doc Ock.",
                            Director = "Sam Raimi",
                            Duracion = 127,
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageUrl = "https://es.web.img3.acsta.net/r_1920_1080/medias/nmedia/18/35/16/02/18380826.jpg",
                            Nombre = "Spider-Man 2",
                            PegiId = 4,
                            UrlDescarga = "https://es.web.img3.acsta.net/r_1920_1080/medias/nmedia/18/35/16/02/18380826.jpg",
                            Valoracion = 5.0
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descripcion = "Basada en el famoso cuento Aladino y la lámpara maravillosa, la trama se sitúa en el exótico paisaje del mítico reino árabe de Agrabah. Aladdin es un ingenioso joven que, a pesar de vivir en un estado de extrema pobreza, sueña con casarse con la bella hija del sultán, la princesa Yasmin. El destino interviene cuando el astuto visir del Sultán, Yafar, recluta a Aladdin para que le ayude a recuperar una lámpara mágica de las profundidades de la Cueva de las Maravillas. El joven encuentra la lámpara, en la que vive un genio que concede tres deseos a quien lo libere.",
                            Director = "John Musker, Ron Clements",
                            Duracion = 87,
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageUrl = "https://es.web.img3.acsta.net/r_1920_1080/img/6c/02/6c022db26a46682b554a0e43a896de17.jpg",
                            Nombre = "Aladdin",
                            PegiId = 1,
                            UrlDescarga = "https://es.web.img3.acsta.net/r_1920_1080/img/6c/02/6c022db26a46682b554a0e43a896de17.jpg",
                            Valoracion = 5.0
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Enabled = true,
                            RoleDescription = "Admin rol",
                            RoleName = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Enabled = true,
                            RoleDescription = "Worker rol",
                            RoleName = "Worker"
                        },
                        new
                        {
                            ID = 3,
                            Enabled = true,
                            RoleDescription = "Customer rol",
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.RoleHasMenu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("RoleID");

                    b.ToTable("RoleHasMenu");

                    b.HasData(
                        new
                        {
                            ID = 9,
                            MenuID = 9,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 10,
                            MenuID = 10,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 1,
                            MenuID = 1,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 2,
                            MenuID = 2,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 3,
                            MenuID = 3,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 4,
                            MenuID = 4,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 5,
                            MenuID = 5,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 6,
                            MenuID = 6,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 7,
                            MenuID = 7,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 8,
                            MenuID = 8,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 11,
                            MenuID = 11,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 14,
                            MenuID = 9,
                            RoleID = 2
                        },
                        new
                        {
                            ID = 15,
                            MenuID = 10,
                            RoleID = 2
                        },
                        new
                        {
                            ID = 12,
                            MenuID = 4,
                            RoleID = 2
                        },
                        new
                        {
                            ID = 13,
                            MenuID = 8,
                            RoleID = 2
                        },
                        new
                        {
                            ID = 16,
                            MenuID = 11,
                            RoleID = 2
                        },
                        new
                        {
                            ID = 17,
                            MenuID = 9,
                            RoleID = 3
                        },
                        new
                        {
                            ID = 18,
                            MenuID = 10,
                            RoleID = 3
                        },
                        new
                        {
                            ID = 19,
                            MenuID = 12,
                            RoleID = 2
                        },
                        new
                        {
                            ID = 20,
                            MenuID = 12,
                            RoleID = 1
                        },
                        new
                        {
                            ID = 21,
                            MenuID = 13,
                            RoleID = 2
                        },
                        new
                        {
                            ID = 22,
                            MenuID = 13,
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Director")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("datetime");

                    b.Property<bool>("HaTerminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<int>("PegiId")
                        .HasColumnType("int");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.Property<string>("UrlDescarga")
                        .HasColumnType("longtext");

                    b.Property<double>("Valoracion")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PegiId");

                    b.ToTable("Serie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "La serie sigue las múltiples tramas de la saga Canción de hielo y fuego.2​ Comienza cuando el Rey Robert Baratheon (Mark Addy) le pide a su viejo amigo Ned Stark (Sean Bean) que realice la función de nuevo consejero real (cargo conocido como la Mano del Rey). La esposa de Ned, Catelyn (Michelle Fairley) recibe una carta de su hermana, Lysa (Kate Dickie) que le da razones para creer que la Casa Lannister, a la cual pertenece Cersei, la esposa del rey, está involucrada en la muerte de la anterior Mano del Rey. Ned debe viajar al sur con el Rey para descubrir el asesino de la Mano del Rey muerto, Jon Arryn (John Standing) y a la misma vez proteger a su familia de los Lannister. Mientras descubre las razones detrás de la muerte de Jon, desentierra el oscuro secreto concerniente a los Lannister que el propio Arryn murió tratando de revelar. ",
                            Director = "David Benioff",
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            HaTerminado = true,
                            ImageUrl = "https://m.media-amazon.com/images/I/91kI5AXwz9L._SY445_.jpg",
                            Nombre = "Juego de tronos",
                            PegiId = 2,
                            Temporada = 1,
                            UrlDescarga = "https://m.media-amazon.com/images/I/91kI5AXwz9L._SY445_.jpg",
                            Valoracion = 5.0
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Walter White decide entrar en el mundo de las drogas ilegales después de que le diagnosticaran cáncer de pulmón. Al ser profesor de química, utiliza sus conocimientos y habilidades para elaborar una metanfetamina junto a un antiguo alumno, Jesse Pinkman (Aaron Paul). Durante sus primeros días, como productores de droga, tienen varios problemas con los distribuidores locales. Además, empiezan a ser famosos, gracias a la droga que producen, y amplian territorio. Walt se crea un apodo, Heisenberg, para darse a conocer en su segunda vida.",
                            Director = "Vince Gilligan",
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            HaTerminado = true,
                            ImageUrl = "https://es.web.img2.acsta.net/r_1920_1080/pictures/18/07/23/11/26/1237965.jpg",
                            Nombre = "Breaking Bad",
                            PegiId = 2,
                            Temporada = 1,
                            UrlDescarga = "https://m.media-amazon.com/images/I/91kI5AXwz9L._SY445_.jpg",
                            Valoracion = 5.0
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descripcion = "Walter decide seguir con el negocio a pesar de todos los conflictos que conlleva. Además, se ve obligado a contratar los servicios de un abogado deshonesto, Saul Goodman, para ayudar al traficante Badger después que fuese arrestado por la policía. Combo, otro de los distribuidores, es asesinado por una banda rival. Mientras todo esto sucede, Jesse comienza una relación con Jane, una joven que se está recuperando de su adicción a las drogas, y Walt encuentra un nuevo socio llamado Gus. Al final de la temporada, la esposa de Walter comienza a sospechar sobre la segunda vida de su marido.",
                            Director = "Vince Gilligan",
                            FechaEstreno = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            HaTerminado = true,
                            ImageUrl = "https://es.web.img3.acsta.net/r_1920_1080/pictures/18/07/23/11/26/1597342.jpg",
                            Nombre = "Breaking Bad",
                            PegiId = 2,
                            Temporada = 2,
                            UrlDescarga = "https://es.web.img3.acsta.net/r_1920_1080/pictures/18/07/23/11/26/1597342.jpg",
                            Valoracion = 5.0
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Worker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CuentaUsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ID");

                    b.HasIndex("CuentaUsuarioID");

                    b.ToTable("Worker");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CuentaUsuarioID = 5,
                            Name = "worker",
                            Phone = "642443214",
                            Surname = "wer"
                        },
                        new
                        {
                            ID = 2,
                            CuentaUsuarioID = 6,
                            Name = "worker",
                            Phone = "642443217",
                            Surname = "worke"
                        });
                });

            modelBuilder.Entity("CinemasRafa.Models.Admin", b =>
                {
                    b.HasOne("CinemasRafa.Models.CuentaUsuario", "CuentaUsuario")
                        .WithMany()
                        .HasForeignKey("CuentaUsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaUsuario");
                });

            modelBuilder.Entity("CinemasRafa.Models.CuentaUsuario", b =>
                {
                    b.HasOne("CinemasRafa.Models.Role", "Role")
                        .WithMany("CuentaUsuarios")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CinemasRafa.Models.Customer", b =>
                {
                    b.HasOne("CinemasRafa.Models.CuentaUsuario", "CuentaUsuario")
                        .WithMany()
                        .HasForeignKey("CuentaUsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaUsuario");
                });

            modelBuilder.Entity("CinemasRafa.Models.Peliculas", b =>
                {
                    b.HasOne("CinemasRafa.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemasRafa.Models.Pegi", "Pegi")
                        .WithMany()
                        .HasForeignKey("PegiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Pegi");
                });

            modelBuilder.Entity("CinemasRafa.Models.RoleHasMenu", b =>
                {
                    b.HasOne("CinemasRafa.Models.Menu", "Menu")
                        .WithMany("RoleHasMenus")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemasRafa.Models.Role", "Role")
                        .WithMany("RoleHasMenus")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CinemasRafa.Models.Series", b =>
                {
                    b.HasOne("CinemasRafa.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemasRafa.Models.Pegi", "Pegi")
                        .WithMany()
                        .HasForeignKey("PegiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Pegi");
                });

            modelBuilder.Entity("CinemasRafa.Models.Worker", b =>
                {
                    b.HasOne("CinemasRafa.Models.CuentaUsuario", "CuentaUsuario")
                        .WithMany()
                        .HasForeignKey("CuentaUsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaUsuario");
                });

            modelBuilder.Entity("CinemasRafa.Models.Menu", b =>
                {
                    b.Navigation("RoleHasMenus");
                });

            modelBuilder.Entity("CinemasRafa.Models.Role", b =>
                {
                    b.Navigation("CuentaUsuarios");

                    b.Navigation("RoleHasMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
